### ISSUE TITLE
Provide an optional attribute in the <tts> tag to hide the text

### ISSUE THREAD

**Issue by ChristianKleineidam** [AwesomeTTS/AwesomeTTS#100]
When learning a new language I have cards that play the sound of a word and require me to type the word:

```
Front:
type.word()<plays soundfile for "l'oesophage">

Back:
l'oesophage
```

I think this frequently provides an useful additional card. I would like to have a `hide=true` attribute that allows me to use AwesomeTTS for this purpose.

**Comment by corpulentcoffee** [comment]
Hey @ChristianKleineidam: Adding a `style="display: none"` attribute will hide the contents of the tag and allow you to do listening comprehension cards like this (you can also use the "visibility" dropdown in the "Add On-the-Fly TTS Tag to Template" window).

**Comment by ChristianKleineidam** [comment]
Thanks that works.
