### ISSUE TITLE
Error message in Anki: 'No JSON object could be decoded' Help possible?

### ISSUE THREAD

**Issue by learningbee1** [AwesomeTTS/AwesomeTTS#109]
Hi there, 

For the 'On-The-Fly Playback' with Awesome TTS - I just downloaded Anki with this add-on but get this error message once I add an on the fly string into the card editor:
'No JSON object could be decoded'

Any help possible or this issue?

**Comment by corpulentcoffee** [comment]
Hi!

Can you share your template?

**Comment by corpulentcoffee** [comment]
(A screenshot or copy+paste of both the error and the template you have
would be helpful.)

**Comment by learningbee1** [comment]
Hi sorry it seems to be working now :)

**Comment by corpulentcoffee** [comment]
Were you using NeoSpeech when you received the message?

**Comment by learningbee1** [comment]
Yes I was actually, has that one been playing up?

**Comment by corpulentcoffee** [comment]
I am not aware of it having problems, but it is the only that I know of that uses JSON. I am going to improve the error handling so it raises a better error message.
