### ISSUE TITLE
When internet connection fails, AwesomeTTS shows same error with every new card

### ISSUE THREAD

**Issue by jaksz** [AwesomeTTS/AwesomeTTS#112]
# Current situation
When you have no internet connection or the internet connection fails, AwesomeTTS will display an error message like this every single time a card gets shown that has no audio buffered yet (= new cards, mostly).

Example:
![- -](https://cloud.githubusercontent.com/assets/13822469/15591825/07e26f02-23a8-11e6-8252-9b44916c77f7.png)

The problem is that it gets displayed **every single time** and you have to click it away for **every** card .

# Preferred situation
AwesomeTTS will display an error message at most once and then not display any more error messages of the same type for at least the current review session.

**Comment by corpulentcoffee** [comment]
Hi!

I agree this should be better.

Until AwesomeTTS is smarter about this, you can uncheck the two "show
errors" checkboxes at Tools > AwesomeTTS > Playback... that will silence
the errors when your Internet connection is down.

Dave

**Comment by jaksz** [comment]
Ah great, thank you!
