### ISSUE TITLE
linguatec fails with "No MP3 was returned for the input."

### ISSUE THREAD

**Issue by dholm** [AwesomeTTS/AwesomeTTS#115]
I've been using the linguatec Italian voices for a while but since a few days ago (maybe three) it always fails with the error:

 No MP3 was returned for the input.

The voices I have tried are "Alice", "Federica", "Paola" and "Luca".

**Comment by corpulentcoffee** [comment]
The Linguatec service itself seems to be down.

(If you go to http://www.linguatec.net/products/tts/voice_reader/vrs15demo and try it there, it won't work either.)

**Comment by dholm** [comment]
Oh, I just went to their main page and since it was up and it has been a few days I assumed it was something else.  Thanks! :)

**Comment by corpulentcoffee** [comment]
Sure thing. I hope it comes back soon, as I use it a lot too.
