### ISSUE TITLE
Oddcast Hugh voice leads to Simon voice

### ISSUE THREAD

**Issue by davidoski77** [AwesomeTTS/AwesomeTTS#123]
Hi,

after last update Oddcast Hugh voice is missing. Instead Hugh leads to Simon voice. I really miss real Hugh as it is my favourite voice of all. Can you please fix the issue?

Thanks in advance.

David

**Comment by corpulentcoffee** [comment]
Unfortunately, I think that Oddcast has a bug in their service.

If you visit http://www.oddcast.com/home/demos/tts/tts_example.php and try some text with "Hugh (UK)" and "Simon (UK)", you will get back the same voice playback.

**Comment by davidoski77** [comment]
I see. It coincided with the AwesomeTTS update and I thought it was AwesomeTTS bug. Thanks for checking.

**Comment by corpulentcoffee** [comment]
Sorry about that! I hope that the voice comes back.
