### ISSUE TITLE
Playback audio translations from Acapela-group in AwesomeTTS has stopped working.

### ISSUE THREAD

**Issue by 96Alex** [AwesomeTTS/AwesomeTTS#125]
I haven't had a problem with it until now for some reason. Anytime I try to add audio to my cards in Anki using Acapela-group translate I get a message saying "Cannot preview input phrase with these settings.  'NoneType' object has no attribute 'groups'." Any ideas on how to fix it?  The other text to audio choices seem to work just fine .

**Comment by corpulentcoffee** [comment]
www.acapela-group.com appears to be down.

**Comment by ninnobr** [comment]
I have the same problem.  "Cannot preview input phrase with these settings. 'NoneType' object has no attribute 'groups'."

**Comment by rathsky** [comment]
That was yesterday, now they play a message like "your usage of the web demo is illegal, we consider legal action". Pity, Sakura's voice was very nice. But maybe there's a workaround?

**Comment by corpulentcoffee** [comment]
It sounds like we're going to have to drop the service.
