### ISSUE TITLE
Support for RHVoice as a TTS service

### ISSUE THREAD

**Issue by aleksejrs** [AwesomeTTS/AwesomeTTS#60]
https://github.com/Olga-Yakovleva/RHVoice

**Comment by corpulentcoffee** [comment]
Thanks, I'll look into supporting this.

If RHVoice has a command line interface that returns the list of available voices and can make wave files, this should be easy to support.

Cheers!

**Comment by aleksejrs** [comment]
The voices are in directories in /usr/local/share/RHVoice/voices, their voice.info files contain the language names.

RHVoice-client receives text on stdin and outputs on stdout (playable with aplay).
RHVoice-test receives and outputs files, but has few options.
It also supports speech-dispatcher (I couldn't test that).

**Comment by corpulentcoffee** [comment]
Hey @aleksejrs --

There's now an experimental branch for this.

You can [download the zip archive](https://github.com/AwesomeTTS/AwesomeTTS/archive/add/rhvoice.zip) for it if you want to test it. In the archive, navigate into `AwesomeTTS-add-rhvoice/addon/` then copy `awesometts` and `AwesomeTTS.py` into your Anki `addons` directory.

Cheers!

**Comment by aleksejrs** [comment]
Thank you: it works (I rebuilt RHVoice with prefix=/usr), including configuration.

**Comment by corpulentcoffee** [comment]
Ah, I will fix it to search `/usr/local/share/RHVoice/voices` automatically in addition to `/usr/share/RHVoice/voices/`. I just did `/usr/share/RHVoice/voices/` initially because that's where my distro's package installed it.

Thanks for trying it out!
