### ISSUE TITLE
Translations from Yandex are not working

### ISSUE THREAD

**Issue by zeem33** [AwesomeTTS/AwesomeTTS#61]
Suddenly stopped working this morning. They work fine on translate.yandex.com

The error is "Cannot preview input phrase with these settings. HTTP Error 502: Bad Gateway"

Thought you should know.

**Comment by corpulentcoffee** [comment]
I'll look into it if it doesn't clear up soon. I use Yandex for Spanish, so this affects me too.

Thanks!

**Comment by corpulentcoffee** [comment]
@zeem33 -- the Yandex errors have cleared up for me -- are you still experiencing HTTP 503 errors from Yandex?

Cheers!

**Comment by zeem33** [comment]
Nope it's working fine now

Thanks!
