### ISSUE TITLE
AwesomeTTS causes double speech readout on Ankidroid

### ISSUE THREAD

**Issue by Chozzle** [AwesomeTTS/AwesomeTTS#62]
Hi,
The AwesomeTTS works amazingly well. I only found one problem, when I put tags on the cards to read out real time speech, it makes the TTS on Android read out twice. Any way around this?
Regards, Carson

**Comment by corpulentcoffee** [comment]
Hey Carson,

AwesomeTTS and AnkiDroid's TTS can sometimes step on each others toes. AnkiDroid's TTS reads the entire card side, so you'll need to do a little tweaking so they can co-exist.

Would you be willing to share your card templates and I'll see what suggestions I have?

Best,
Dave

**Comment by Chozzle** [comment]
Hi Dave,
Thanks for the quick response. I simply inserted a AwesomeTTS link in the
back side of the card, like this. On desktop it works perfect, but doubles
up in ankidroid. Cheers!
Carson

{{FrontSide}}


<hr id=answer>


{{English}}


<tts service="spanishdict" voice="en">{{English}}</tts>

**Comment by corpulentcoffee** [comment]
Hi Carson,

For your usage, you can change your template to:

    {{FrontSide}}

    <hr id=answer>

    <tts service="spanishdict" voice="en">{{English}}</tts>

This way, the English text will only be on the back side once and AnkiDroid's TTS will only read it once.

(If you have `tts { display: none }` in your "Styling" rules, you need to remove it for the text to be visible.)

Best,
Dave

**Comment by corpulentcoffee** [comment]
... and make sure you synchronize your collection with your device after you change your template. :)

Best,
Dave

**Comment by Chozzle** [comment]
Thanks Dave, that fixed my problem!

**Comment by corpulentcoffee** [comment]
Glad to hear! Enjoy the add-on and good luck with your studies.

Best,
Dave

**Comment by porfirio1830** [comment]
Dear Sirs,  (android+tts)
Please,  tell me how to:
1. Install the addon "awesome TTS".
2. Use this addon with android google tts engine.
For. ankiDROID
Note: awesomeTTS works pretty well with windows-anki, 
but I don't know how to use it with android-anki.
Thanks for your attention.

**Comment by porfirio1830** [comment]
Dejar sirs,
If I install python  in android, could I use the addons for anki-windows with ankiDROID?
Thanks for tour attention.

**Comment by corpulentcoffee** [comment]
Hey @porfirio1830 --

AnkiDroid isn't the same as the desktop version of Anki, so you cannot use the desktop add-ons in AnkiDroid. AnkiDroid *does* have a text-to-speech feature that can read the text from your cards to you using the text-to-speech engines on your phone, but it's not the same as AwesomeTTS.

If you want to use audio from AwesomeTTS on AnkiDroid (or anywhere), the best thing to do is to use the features in AwesomeTTS that store MP3s in your collection: you can do this [one at a time in the note editor](https://ankiatts.appspot.com/usage/editor) or [in bulk using the card browser](https://ankiatts.appspot.com/usage/browser).
