### ISSUE TITLE
Keep field value in a saved file name

### ISSUE THREAD

**Issue by szpak** [AwesomeTTS/AwesomeTTS#63]
It could be useful sometimes to have a textual value of a text in a generated (and saved) file (e.g. `dog-service_name-uuid.mp3`).

**Comment by corpulentcoffee** [comment]
I agree this would be useful. I'm all for it if we can do this in a way that yields filenames that are *truly portable* given any input language *and* between the Anki desktop clients on Windows / Linux / OS X, the mobile clients on Android / iOS, and AnkiWeb. It might be too ambitious for the current 2.0.x branch of Anki, but it might work out in the future.

**Comment by corpulentcoffee** [comment]
See also #69.

**Comment by corpulentcoffee** [comment]
Hey @szpak -- I now have an experimental build of AwesomeTTS that will generate human-readable filenames for MP3s stored in your Anki collection. If you're interested in testing it out, let me know and I can send along instructions (it's the `human-filenames` branch on the repo).

**Comment by szpak** [comment]
Sure. To send me instructions you can use the email address visible in my GitHub profile or put it somewhere publicly.

**Comment by szpak** [comment]
In the meantime I have found those [instructions](https://github.com/AwesomeTTS/AwesomeTTS/issues/69#issuecomment-111933441) and were able to generate some media files in a human readable format for new cards. I spotted no errors. I tried break the system with using problematic characters like `$`, but they seem to be properly removed. Thanks for that feature!

Tested with Linux and Android.

**Comment by corpulentcoffee** [comment]
Hey @szpak!

Yes, I was going to send you those instructions, but I was waiting to see if the problem on Windows could be replicated or not. I didn't know what operating system you were on, and I didn't want you to run into the exact same problem!

Thanks for testing, and sorry for the delay!

**Comment by szpak** [comment]
> Tested with Linux and Android.

:)

**Comment by szpak** [comment]
And no problem about the delay. I'm always open to contribute to useful FOSS projects :).
