### ISSUE TITLE
In Card Browser only show selected deck's fieldnames

### ISSUE THREAD

**Issue by forkrul** [AwesomeTTS/AwesomeTTS#64]
Thanks for a great plugin.

I have a large amount of custom decks that have multiple fieldnames each. My suggestion is that on selecting a deck name (in the left panel) that the Mass Generator only display the field names for the cards in that particular selected deck.

**Example problem**: Select a deck on left - select some cards in the browser window - click on mass generate menu item. All fields from all cards in all decks show up - this is very difficult to distinguish, which field is from which deck.

**Example solution**: Select a deck on the left - (optional) select some cards in the browser window - click on mass generate menu item. Only fields from the (optional) selected cards, or only fields from the selected deck should show up. 

An alternative to this might be to prepend the fieldnames with the deck that they are from, in the selection list - this would make it easier to find the field and distinguish it from others.

**Temporary workaround**: 
1. Export only a given deck, with sheduling data and media. 
2. Reimport on a clean user. 
3. Mass generate - as only limited fields are shown. 
4. Export. 
5. Reimport to original user.

**Comment by corpulentcoffee** [comment]
Hello!

What version of AwesomeTTS are you running? The old "beta" releases had this problem, but the newer releases should be fine.

Specifically, 

- thru v1.0 beta 10, the mass generator would display [an unsorted list of every field from every card type in the collection, including any duplicate fields](https://github.com/AwesomeTTS/AwesomeTTS/blob/v1.0.0-beta.10/awesometts/main.py#L249)
- in later versions, the mass generator displays [a sorted list with unique fields only](https://github.com/AwesomeTTS/AwesomeTTS/blob/v1.3.1/addon/awesometts/gui/generator.py#L187) specifically from [only the cards you actually have selected in the card browser](https://github.com/AwesomeTTS/AwesomeTTS/blob/v1.3.1/addon/awesometts/gui/generator.py#L177)

Let me know what version you are running and we can figure out what's going on.

Cheers!
Dave

**Comment by forkrul** [comment]
Hi Dave

Updated to latest on the Anki plugin site (I was somehow under the impression Anki would automatically update plugins, I guess not). 

Interface pop-up now moved from Modify to its own top-level menu - and new GUI. version 1.3.1 now running :) and it is everything I've hoped for.

I can do away with my cobbled together python script (pulled tts from Google Translate) now, finally.

Can I donate somewhere?

**Comment by corpulentcoffee** [comment]
Anki only checks for updates for itself; it doesn't do updates for the add-ons, unfortunately. The new version of AwesomeTTS that you have now *will* check for updates, though, but it's a custom thing in the AwesomeTTS code.

No donations necessary -- bug reports and improvements are all the contributions I want! Good luck with your studies. Cheers!
