### ISSUE TITLE
AwesomeTTS throws an "error" message for pretty much everything, for whatever reason, and I have no idea why.

### ISSUE THREAD

**Issue by CheeseTurtle** [AwesomeTTS/AwesomeTTS#66]
Hello! Every time I do anything even remotely involving the AwesomeTTS plugin, I get an error message in a popup dialog. All of them start with something like this: 
       
     An error occurred. It may have been caused by a harmless bug, or your deck may have a problem. 
     To confirm it's not a problem with your deck, please run Tools > Check Database. 
     If that doesn't fix the problem, please copy the following into a bug report:

What comes after depends on the context. When trying to open the configuration dialog, the error message ends with: `DEBUG:AwesomeTTS:Showing 'AwesomeTTS: Configuration' dialog`.

When I try to manage my config presets, I get `DEBUG:AwesomeTTS:Restoring options for google
DEBUG:AwesomeTTS:Showing 'AwesomeTTS: Manage Service Presets' dialog`. (Not sure why this constitutes an error.)

When I try to "Record and Insert an Audio Clip Here" in the Browser, I get `DEBUG:AwesomeTTS:Constructing Add TTS Audio to Note (EditorGenerator) dialog
DEBUG:AwesomeTTS:Constructing panel for google
DEBUG:AwesomeTTS:Restoring options for google
DEBUG:AwesomeTTS:Showing 'AwesomeTTS: Add TTS Audio to Note' dialog
DEBUG:AwesomeTTS:Transformation using ['early exit']: (empty string)
DEBUG:AwesomeTTS:Transformation using [('clozes_braced', 'anki'), 'html', 'whitespace', 'sounds_univ', 'filenames', 'ellipses', 'whitespace']: quando`.

All of these things seem more like debug messages reporting what's going on than actual errors. Do I have something configured to where it's showing me dev debug stuff? There's a time and place for that kind of thing, but it really is annoying when I'm trying to make or review my cards.

Thank you!

**Comment by corpulentcoffee** [comment]
Yes, those are all debug messages... But they should very much be turned
off by default *and* even when they are turned on, they should not be
triggering a dialog.

Is there anything unusual about your system setup? What operating system
and version of Anki do you have?

**Comment by CheeseTurtle** [comment]
I'm running Anki 2.0.32 on Windows 7 Home Premium SP1.

**Comment by corpulentcoffee** [comment]
That's really strange that you're running into this. The only thing I can think of is that you might have another add-on installed that is doing something to the logger mechanism.

Anyway, even if we can't figure out what's wrong with your logger, we can do a workaround.

Are you comfortable with any code editors on Windows (e.g. Notepad++)? If so, go to your Documents folder and pop open `Anki\addons\awesometts\__init__.py` and find this part:

    logger = Logger(
        name='AwesomeTTS',
        handlers=dict(
            debug_file=logging.FileHandler(paths.LOG,
                                           encoding='utf-8',
                                           delay=True),
            debug_stdout=logging.StreamHandler(sys.stdout),
        ) if paths.ADDON_IN_ASCII else dict(
            debug_file=logging.NullHandler(),
            debug_stdout=logging.NullHandler(),
        ),
        formatter=logging.Formatter(
            "[%(threadName)s %(asctime)s] %(pathname)s@%(lineno)d %(levelname)s\n"
            "%(message)s\n",
            "%H:%M:%S",
        ),
    )

Replace it entirely with this:

    logger = Bundle(
        activate=lambda *a, **k: None,
        debug=lambda *a, **k: None,
        error=lambda *a, **k: None,
        info=lambda *a, **k: None,
        warn=lambda *a, **k: None,
    )

**Comment by corpulentcoffee** [comment]
The logging stuff will be removed from 1.5.0, as someone else has reported a similar issue.
