### ISSUE TITLE
Do not play what was just downloaded for a different card.

### ISSUE THREAD

**Issue by aleksejrs** [AwesomeTTS/AwesomeTTS#67]
1. Choose a very slow remote service for on-the-fly playback.
2. Review a card with text that should be played by that service, without waiting for it to play.
3. Review a few other cards (maybe not using that service).
4. Hear the piece of text from step 2.

**Comment by aleksejrs** [comment]
It was [ImTranslator](https://ankiatts.appspot.com/services/imtranslator).

**Comment by corpulentcoffee** [comment]
Yeah, this behavior is pretty annoying if remote services are being slow and you're reviewing your cards quickly. This should be fixable if Anki exposes the card ID that's currently being reviewed somewhere, which I think it does, so I'll look into it.

**Comment by corpulentcoffee** [comment]
Hey @aleksejrs --

I've fixed this on the develop branch... it'll go out in the next version.

Cheers!
