### ISSUE TITLE
I'd like to set back of card as the mp3 file's name - is that possible ?

### ISSUE THREAD

**Issue by turgutbekil** [AwesomeTTS/AwesomeTTS#69]
Hi; 
Im learning english and my native language is turkish. I have cards , english word on the front, turkish translation word on the back. 
For example : book (on the front) / kitap (on the back) .. I d like to generate mp3 file for this card with the name : kitap.mp3

or a comination of both sides like : book_kitap.mp3 is this possible ?

that would be awesome! :)

ps:currently awesome is generating mp3 files with names like: *google-0a70e1fa-8479cd2c-597b51e7-742ad12d-395c06ba* which is impossible to recogise the word (my aim is to use files in my mp3 player too).

**Comment by corpulentcoffee** [comment]
Hello!

It is not possible to do this with AwesomeTTS right now.

I want to support this, but it is not easy to do it correctly. The names must work across Windows, Linux, OS X, AnkiWeb, AnkiDroid, and AnkiMobile *and* they must work for any input, including for languages that do not use a Latin character set (like Thai, Japanese, Chinese, Arabic).

Thank you for telling me you want this. I know other people want it too. I will experiment with this soon and see if I can make human-readable filenames an option that you can enable.

Best of luck with your studies. English is hard, but you already write well. :+1:

**Comment by turgutbekil** [comment]
Thank u Dave. People like u making the world better :)
best!

**Comment by corpulentcoffee** [comment]
Hey @turgutbekil -- I now have an experimental build of AwesomeTTS that will generate human-readable filenames for MP3s stored in your Anki collection. If you're interested in testing it out, let me know and I can send along instructions.

**Comment by turgutbekil** [comment]
Hi Dave; Im ready to test it :) lets do.

**Comment by corpulentcoffee** [comment]
Hi @turgutbekil !

Great, I really appreciate it. This is what you need to do:

1. close Anki if it is running
2. find your Anki add-on directory (usually in your Documents then `Anki` then `addons`)
2. download https://github.com/AwesomeTTS/AwesomeTTS/archive/human-filenames.zip
3. open the archive
4. navigate into `AwesomeTTS-human-filenames`, then `addon`
5. copy `awesometts` and `AwesomeTTS.py` into your Anki add-on directory
6. start Anki
7. open the AwesomeTTS configuration screen (Tools then AwesomeTTS from the Anki main window)
8. go to the MP3s tab
9. change "Filenames should be" to "human-readable"
     ![screenshot_2015-06-15_00-37-43](https://cloud.githubusercontent.com/assets/3958448/8153677/cec14fd0-12f6-11e5-811b-5ddfa91cf2e7.png)

Once all that is done, if you make MP3s in the the Note Editor or the Card Browser, you will get a human-readable filename in your collection. (Your old MP3s will stay the same.)

**Comment by turgutbekil** [comment]
Hi Dave; 
I removed all sound tags in anki and then all cards and decks in anki (this is not a problem for me Im also using another app in my smart phone). Then I did the instructions of yours and then started to add sounds from zero: 
1-first its too slow.
2-I track the progres but it says that all of it failed (but the progress is going on without a success)
![2015-06-15_09-29-58](https://cloud.githubusercontent.com/assets/12607840/8154326/be08c826-1341-11e5-80ff-2489592a79c3.png)

**Comment by corpulentcoffee** [comment]
Hello!

What error message do you get at the end of the mass generation?

**Comment by turgutbekil** [comment]
Hi Dave; 
I did'nt wait until to the end since its too slow.. Should I wait? do you think that it will give a conclusion error message at the end of the mass generation ?

**Comment by corpulentcoffee** [comment]
Yes, there is a summary at the end.

What happens if you just try to generate a single MP3 with the Note Editor?

**Comment by corpulentcoffee** [comment]
(Also: the 30-second delays are so Google and other online services do not ban you for downloading MP3s too fast. You change this by adjusting the "After X operations, sleep for X seconds" bit on that configuration screen. If you are too aggressive, Google might ban your IP address, though.)

**Comment by corpulentcoffee** [comment]
Hi @turgutbekil !

By the way, if you don't have time to find the error message, just let me know which version of Windows you're running and anything interesting about your setup (Turkish install?), and I'll try to replicate your error. :)  I already know that you're studying with English cards.

**Comment by turgutbekil** [comment]
Hi Dave ;
Sorry for late answer man, Im also at the office and its very bussy sometimes. Im using an 64 bit Windows 8 (turkish) and Anki is also in turkish. I will also create a small deck in order to see the result message.

**Comment by turgutbekil** [comment]
![2015-06-17_09-11-55](https://cloud.githubusercontent.com/assets/12607840/8200669/1b80002e-14d1-11e5-885b-a5ad872834b7.png)

**Comment by turgutbekil** [comment]
Its working ! :) I create a small deck and its done. But in another deck it didnt work. I will keep testing and try to understand if  there is any pattern or its fully working well.

**Comment by turgutbekil** [comment]
its seems that its working man. congrats :) maybe last time I dind't make a restart. this time its working because of restart. Is it possible to make it write any side of the card ? Or both? At the moment its like englishword.mp3, can it be ? turkishword.mp3 or a combination : english_turkish.mp3 ? :)

**Comment by turgutbekil** [comment]
I made a special deck for this like:  first text is a combination of both sides. So the result is successfull :)  not that helps me alot
![2015-06-17_09-47-14](https://cloud.githubusercontent.com/assets/12607840/8201095/099cd17a-14d6-11e5-9f7b-a0753cc64f4a.png)

**Comment by turgutbekil** [comment]
BUT,, when I do this google engine reads full of it :) so its not a good way. So is there a way to edit human readable file name? Is it possible to make it write any side of the card ? Or both? At the moment its like englishword.mp3, can it be ? turkishword.mp3 or a combination : english_turkish.mp3 ? :)

**Comment by corpulentcoffee** [comment]
I am not sure how to do filenames like "english_turkish.mp3" yet.

The English part of the filename is easy, because it's the text that AwesomeTTS uses to make the audio, but AwesomeTTS doesn't know which of your note fields to get the Turkish word from.

Is your Turkish word always in a field called "Turkish" (or similar)? Maybe I can make it so you can specify note field names in the filename template string.

**Comment by turgutbekil** [comment]
Flashcards usually have 2 sides like first side and second side. For this I create a excel file 1 colunm is english and second is turkish and save it as csv. Anki understand this as front side and back side. When I start awesome I think I choose and say it to read front side (english).  So in sofware if we can set the file name like  <frontside>_<backside>.mp3 or  <backside>.mp3 it would be awesome . 

But its still awesome. man! no worries :) thank you. by the way will you publish this now?

**Comment by corpulentcoffee** [comment]
Before I publish it, I want to try to add support for putting another field into the filename for you.

If all your Turkish words are in the "Back" field ("Geri"?), this *should* be doable.

**Comment by turgutbekil** [comment]
Hi,  Dave, they are usually on back. (2.side)..  Thanks for all ! .. tell me if you visit istanbul man, you have a couch and a free guide here ok ! :)

**Comment by corpulentcoffee** [comment]
Hey @turgutbekil -- There's a new version of the add-on available that might help. You can follow the [same instructions as before](#issuecomment-111933441) if you want to try it.

On the configuration screen, add `{{Back}}` or `{{Geri}}` (or whatever **note field** has your Turkish text in it) to the "format human-readable filenames as ..." box.

So you might end up with: `{{text}} - {{Back}} ({{service}} {{voice}})`
... or maybe: `{{text}} - {{Geri}} ({{service}} {{voice}})`

Then try generating an MP3 for a note that has that field.

**Comment by turgutbekil** [comment]
Hi Dave; 
Tested. Its working :) many thanks. 
![2015-06-22_21-24-31](https://cloud.githubusercontent.com/assets/12607840/8289464/3c416ebc-1925-11e5-913a-2171245e455f.png)

**Comment by corpulentcoffee** [comment]
Thanks @turgutbekil -- That is good.

I'm going to publish this in the next version of AwesomeTTS. Thanks again for your help testing.

Istanbul is a beautiful city... hope I get to visit one day.

Cheers!

**Comment by george84** [comment]
Hey @corpulentcoffee 

Thank you for this feature. I tested on Windows for arabic-english. It gives me filenames like [sound:جواز ات - Pass (google ar).mp3] and it works well.

**Comment by corpulentcoffee** [comment]
Hey @george84 -- thanks for testing -- thanks especially testing something that doesn't use a Latin character set on Windows -- I appreciate it!

**Comment by george84** [comment]
You are welcome

I also exported collection from windows and imported on android. It 
works too! Fantastic.

Am 30.06.2015 um 17:13 schrieb Dave Shifflett:
>
> Hey @george84 <https://github.com/george84> -- thanks for testing -- 
> thanks especially testing something that doesn't use a Latin character 
> set on Windows -- I appreciate it!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/AwesomeTTS/AwesomeTTS/issues/69#issuecomment-117222291>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by szpak** [comment]
I've just realized that 1.4.1 which restore compatibility with Google Translate does not contain a (very useful) ability to save field names in filenames from 1.5.0-dev (#63). Do you plan to release 1.5.0 in the predictable future?

**Comment by corpulentcoffee** [comment]
Hey @szpak !

I haven't released 1.5 yet because I realized that there are a few bugs with the human-readable filenames (notably, any of the AwesomeTTS features that operate on "sounds generated by AwesomeTTS" don't work anymore). I'm fixing these now.

Once I fix those, I just need to do a bit of testing on 1.5 before releasing it.

For what it's worth: the latest v1.5.0-dev builds have the Google Translate compatibility fixes, too, if you want to run that.

**Comment by szpak** [comment]
Thanks for a tip @corpulentcoffee! I grabbed the latest version from the `develop` branch and put it into Anki directory. Human readable name works as expected.
