### ISSUE TITLE
Support for VoiceText as a TTS service

### ISSUE THREAD

**Issue by cjkaminski** [AwesomeTTS/AwesomeTTS#71]
Google's TTS service is nice, but it's cadence and rhythm for Japanese sounds very mechanical. There are a couple of other services in Japan that are worlds better: Voiceroid+ and VoiceText.

Voiceroid+ is the most popular product in its category. It has an API somewhere because the folks who develop the Visual Novel Reader software seem to have implemented it, however I can't find any documentation. 

VoiceText, on the other hand, has a free and well-documented API. You can find all the information here: https://cloud.voicetext.jp/webapi/

The biggest challenge that I can see with implementation of VoiceText may be the resulting audio files. VoiceText returns results in WAV, ACC, or Ogg. MP3 does not appear to be an option.

If it's possible, I would love to have support for this in the future. Many thanks and let me know if I can help make this happen!

**Comment by cjkaminski** [comment]
I read in one of the other threads that ANKI has lame support. Would that address my previous concern about the format issue?

**Comment by JZL003** [comment]
While I am not qualified to answer about awesometts and integration with your different plugins, it is very possible to do all the work manually. With the apis you've provided, you could get the audio in whatever format, then use LAME or even cloudconvert.com for the conversion (are you sure anki doesn't support those formats, I haven't tried those in particular but I've had luck with a lot of formats). Then you can use anki's built in find and replace to add the audio tags dynamically to each note/card. I know that sounds like a lot but it really isn't that bad

**Comment by corpulentcoffee** [comment]
Hey @cjkaminski --

I'll take a look soon at that API and see what I find out. Whether or not we can use it in AwesomeTTS probably just depends on the terms and conditions of the API and that sort of thing.

Anki is generally distributed with LAME so AwesomeTTS can use that to transcode audio into the MP3 format, so that is not a problem (in fact, many of the other services already use this).

**Comment by cjkaminski** [comment]
Thanks for the super quick replies guys!

@JZL003 - Thanks for the tips! I'm happy to do the work myself. Ideally, I'd love to see VoiceText as an easy option for less technical people too.

@corpulentcoffee - Thanks for taking a look! As you've probably noticed their whole website is in Japanese, but machine translation seems to do a pretty good job parsing that one.

**Comment by corpulentcoffee** [comment]
Hey @cjkaminski -- This is in-progess and I mostly have VoiceText working nicely in AwesomeTTS. I still need to add some sort of facility for users to fill in their API keys, and I think that's the only thing that's left before this can land in AwesomeTTS 1.5.0.

Thanks for the suggestion! The playback sounds nice with this service.

**Comment by cjkaminski** [comment]
Right on. Thanks for implementing this feature! I'm very excited to give it a spin!

**Comment by corpulentcoffee** [comment]
Hey @cjkaminski, if you are interested in testing this new service in AwesomeTTS before it gets released, let me know. That would be helpful for me to be confident that it works properly, as I do not study Japanese myself.

**Comment by cjkaminski** [comment]
It would be my pleasure! I'll send you an email to sort out the details.

**Comment by corpulentcoffee** [comment]
@cjkaminski -- Here's what you do for the version of AwesomeTTS with VoiceText:

1. close Anki if it is running
2. find your Anki add-on directory (usually in your Documents directory then `Anki` then `addons`)
3. download https://github.com/AwesomeTTS/AwesomeTTS/archive/voicetext-71.zip
4. open the archive
5. navigate into `AwesomeTTS-voicetext-71`, then `addon`
6. copy the `awesometts` directory and `AwesomeTTS.py` into your Anki add-on directory, replacing the existing ones
7. start Anki

Once in, you just open one of the AwesomeTTS dialogs as usual, enter your API key, and hopefully things will work!
