### ISSUE TITLE
Add sound for both front and back of the card

### ISSUE THREAD

**Issue by ooker777** [AwesomeTTS/AwesomeTTS#74]
It will be handy if I want to have sound in both the front and the back of the card. It will also keep the audio file not to be duplicated (if AwesomeTTS download it again).
![capture](https://cloud.githubusercontent.com/assets/6695517/9149050/039498d6-3dc0-11e5-8f79-e3a2b671c259.PNG)

**Comment by corpulentcoffee** [comment]
Hello!

If you want a sound to play on both the front and back side of your card, one option is to

1. add a field called "TTS"
2. add the `{{TTS}}` tag to your front template
3. add the `{{TTS}}` tag to your back template
4. run the mass generator from the Front field to your new "TTS" field

That said, I agree that this dialog needs to be more powerful.

**Comment by ooker777** [comment]
can I add that filed for the whole deck? I can't find it anywhere

**Comment by corpulentcoffee** [comment]
Go to the screen where you add or edit a note, then you can click "Fields" then "Add" to add a new field. Once you do that, from that same screen, you can click "Cards" to edit your templates.

**Comment by ooker777** [comment]
That's pretty smart. I would suggest you to add this into your guide. Thanks.
