### ISSUE TITLE
Feature request: Allow replacement of newlines

### ISSUE THREAD

**Issue by noinkling** [AwesomeTTS/AwesomeTTS#76]
The text handling options are really nice for manipulating on-the-fly text, but there currently doesn't seem to be a way to replace newlines/linebreaks.

To explain my use case I sometimes have a single field that looks something like this:

```
médico
médica
```

I would like a pause between the two words, because at the moment the linebreak simply acts like a space so in the audio "médica" is said in rapid succession after "médico". My thought was to replace the linebreak with an ellipsis or comma using the addon's configuration, but attempts at this have failed. Regular expressions like `\n` or `[\n\r]` don't work, and neither does pasting a linebreak character directly. I suspect this is because whatever preprocessing you're doing replaces any newlines with spaces before the regular expression can do its thing. I also tried pasting it in the "Replace ... characters with an ellipsis" box but it wouldn't let me.

Of course I could just put an ellipsis or comma right in the field itself, but that looks ugly and kinda defeats the purpose. I could probably also use some sort of invisible character and try and replace that instead, but it seems like a pretty hacky workaround.

So what I propose is having a checkbox next to the current "Replace ... characters with an ellipsis" option to enable it for linebreaks.

**Comment by corpulentcoffee** [comment]
On Tue, Sep 8, 2015 at 7:08 AM, noinkling wrote:

> I suspect this is because whatever preprocessing you're doing replaces any
> newlines with spaces before the regular expression can do its thing.


Yes, you're correct. This is what happens.

The difficulty with the Anki templates and the regex feature is that people
have all matters of newlines and indentations for formatting purposes, so
collapsing all whitespace down to a single space makes text replacement
more predictable... it makes your use case impossible, though.

However, I should be able to do a special "replace newlines with an
ellipsis" fairly easily for 1.5 so you can do this.

**Comment by noinkling** [comment]
Thanks for considering it :+1: Awesome addon by the way, has some really nice functionality.

**Comment by corpulentcoffee** [comment]
Hey @noinkling -- feel free to try the AwesomeTTS build at https://github.com/AwesomeTTS/AwesomeTTS/archive/ellipsize-newlines-76.zip for this feature.

Instructions:

1. close Anki if it is running
2. find your Anki add-on directory (usually in your Documents directory then `Anki` then `addons`)
3. download https://github.com/AwesomeTTS/AwesomeTTS/archive/ellipsize-newlines-76.zip
4. open the archive
5. navigate into `AwesomeTTS-ellipsize-newlines-76`, then `addon`
6. copy the `awesometts` directory and `AwesomeTTS.py` into your Anki add-on directory, replacing the existing ones
7. start Anki

**Comment by noinkling** [comment]
Tried it, seems to work just fine, thanks :+1:
