### ISSUE TITLE
HTTP 503 error using Google Translator

### ISSUE THREAD

**Issue by leo-one** [AwesomeTTS/AwesomeTTS#79]
Hi,

My English class is using Anki and the AwesomeTTS to train English and we are receiving HTTP 503 just after use Google Translate 3 or 4 times.
We are from different states of Brazil and we don't share the same IP.

I've tried to find in the code any application private key that could be limiting the quantity of requests, but I didn't find any. I realized that an idx is being passed as parameter to Google Translate request, but I couldn't identify the purpose or possible values of this variable.

I will appreciate any clarification about this question.

**Comment by corpulentcoffee** [comment]
I have also noticed that Google Translate has recently much stricter about the number of requests it will accept. I'm looking at possible workarounds, but for now, since you are studying English, you may want to try using another one of the online TTS services.

**Comment by SauloSilva** [comment]
@leo-one I've this same problem. 
But now, suggestions of the @corpulentcoffee, I am using another TTS service that seemed with google.
**OS x speech Synthesis** in this case only work on SO OSx or **Yandex** for all SO. 

<img width="647" alt="screenshot 2015-10-18 03 43 36" src="https://cloud.githubusercontent.com/assets/1027336/10562880/c7804520-7550-11e5-9494-0c3485d16425.png">
<img width="651" alt="screenshot 2015-10-18 03 44 11" src="https://cloud.githubusercontent.com/assets/1027336/10562881/c7809188-7550-11e5-9ab5-c93c209b9807.png">

**Comment by corpulentcoffee** [comment]
Hi @SauloSilva. Sorry that Google is not working. At least, since you are also studying English, there are many other services available.

I have some ideas about how to make Google work again, but nothing definite yet.

**Comment by corpulentcoffee** [comment]
Support forum post at https://anki.tenderapp.com/discussions/add-ons/5437 also.

**Comment by szpak** [comment]
:+1:

**Comment by SauloSilva** [comment]
Thanks @corpulentcoffee :+1:
