### ISSUE TITLE
HTTP error 403 on audio loading when Google Translator is used

### ISSUE THREAD

**Issue by evgenybf** [AwesomeTTS/AwesomeTTS#83]
Hello,

AwesomeTTS has stopped working since yesterday evening:

```
INFO:root:Initializing Oxford Dictionary service...
INFO:root:Oxford Dictionary service initialized
INFO:root:Initializing TTS-API.com service...
INFO:root:TTS-API.com service initialized
INFO:root:Initializing Yandex.Translate service...
INFO:root:Yandex.Translate service initialized
DEBUG:root:Building the options list for Google Translate
DEBUG:root:Constructing panel for google
DEBUG:root:Retrieving the description for Google Translate
DEBUG:root:Restoring options for google
DEBUG:root:Showing 'AwesomeTTS: Add TTS Audio to Selected Notes' dialog
DEBUG:root:Constructing Generating MP3s (_Progress) dialog
DEBUG:root:Showing 'AwesomeTTS: Generating MP3s' dialog
DEBUG:root:Transformation using [('clozes_braced', 'anki'), 'html', 'whitespace', 'sounds_univ', 'filenames', 'ellipses', 'whitespace']: arranging
DEBUG:root:Call for 'google' w/ {'voice': u'en-GB'}
DEBUG:root:Validated and normalized 'voice' with failure count of 0
DEBUG:root:Parsed call to 'google' w/ {'voice': 'en-GB'} and "arranging" at <homedir>Anki\addons\awesometts\.cache\google-cc0281fd-a5b1ca88-06453b74-9b00e288-655eb610.mp3 (cache miss)
DEBUG:root:Spawned thread [1]; pool={1: {'worker': <awesometts.router._Worker object at 0x05F17B70>, 'callback': <function <lambda> at 0x05BB2330>, 'done': False}}
DEBUG:root:GET https://translate.google.com/translate_tts?textlen=9&idx=0&q=arranging&tl=en-GB&client=t&tk=86854%7C74610&total=1&ie=UTF-8 for web request
DEBUG:root:Exception from thread [1] (HTTP Error 403: Forbidden); executing callback
!!! Traceback (most recent call last):
!!!   File "<homedir>Anki\addons\awesometts\router.py", line 881, in run
!!!     self._task()
!!!   File "<homedir>Anki\addons\awesometts\router.py", line 453, in <lambda>
!!!     task=lambda: service['instance'].run(text, options, path),
!!!   File "<homedir>Anki\addons\awesometts\service\google.py", line 196, in run
!!!     else io_error
!!! HTTPError: HTTP Error 403: Forbidden
!!! 
DEBUG:root:Reaped thread [1]; pool={}
```

**Comment by evgenybf** [comment]
Oh, sorry. Found your message on Anki site:
***Google Translate has recently become unreliable again. If possible, switch to another online TTS service that offers your language, like Yandex.Translate.***

**Comment by corpulentcoffee** [comment]
No worries.

I'm not sure what to do about Google Translate at the moment. The fact that it's not working again is problematic because not only is it the default service in AwesomeTTS, but it also offers by far the most languages of the online services.

The *last* time Google broke, I started working on a [solution to actually run a WebKit browser inside of Anki to download the audio](https://github.com/AwesomeTTS/AwesomeTTS/compare/trash/google), but this has its own reliability issues, unfortunately. I might need to look at resurrecting it.

**Comment by corpulentcoffee** [comment]
The bad news is that it doesn't look like Google will be coming back to AwesomeTTS in the next version... at least not until Anki ships with newer versions of the Qt and WebKit libraries. I'm going to close this issue out for now, but will revisit it after a new major version of Anki is released.

If your language is not well-supported by the other AwesomeTTS services but you know of another text-to-speech service that does have good support, please suggest it, and I'll look into adding integration for that.
