### ISSUE TITLE
Generating audio with Google Translate throws 403 Forbidden error

### ISSUE THREAD

**Issue by jeremybeasley** [AwesomeTTS/AwesomeTTS#86]
In the past week or so, generating audio using "Google Translate" as the configure service results in a 403 error. First time I'm seeing this. See screenshots below. 

![screen shot 2016-01-03 at 10 40 20 pm](https://cloud.githubusercontent.com/assets/1394242/12084646/48a8ce54-b26b-11e5-987e-75d6f9022f3b.png)
![screen shot 2016-01-03 at 10 40 33 pm](https://cloud.githubusercontent.com/assets/1394242/12084647/48c5d116-b26b-11e5-8ea7-80a79d716aca.png)

Thankfully, I can fall back to other services. Thanks for the product. Easily the best plugin on Anki. Cheers.

**Comment by szpak** [comment]
Duplicated of #83.

**Comment by corpulentcoffee** [comment]
Hey @jeremybeasley !

Yes, I know about the Google problem. Unfortunately, I am a bit stuck at coming up with a solution that doesn't require shipping Google's hash proprietary function with the add-on, which makes me uncomfortable and would probably break quickly. I came up with a solution that has Anki run Google Translate headlessly inside of WebKit, but it only works with very new versions of the PyQt/Qt/WebKit libraries (and unfortunately, on Windows and OS X, Anki ships with fairly old libraries).

Anyway, AwesomeTTS v1.6 is going to ship with three new services to make up for the (hopefully temporary?) loss of Google: NAVER, NeoSpeech, and Oddcast. I see that you're using the local OS X speech facilities as a fallback right now, but let me know if there are other services that you know of that would be helpful to use from the add-on that would help take the sting out of losing Google.

Cheers!

**Comment by jeremybeasley** [comment]
@corpulentcoffee Sorry for the slow reply. I see that you've resolved this with newer releases. 
@szpak Thanks for flagging as a dupe. I was being lazy and didn't see the other issue.

**Comment by corpulentcoffee** [comment]
@jeremybeasley No worries! I have not really "resolved" it, but I am adding other services that people have been suggesting to make up for the loss of Google Translate.

**Comment by jeremybeasley** [comment]
@corpulentcoffee amens sense. I'm going to close this since it's a dupe of #83
