### ISSUE TITLE
iSpeech support

### ISSUE THREAD

**Issue by lucwastiaux** [AwesomeTTS/AwesomeTTS#93]
I am looking to generate cantonese audio, I used iSpeech a few years ago with some custom python scripts, then moved to Google Translate after discovering AwesomeTTS. I'm very saddened  by the loss of Google Translate, but as a second best choice, i'd love to have iSpeech support: http://www.ispeech.org/#/home

Any thoughts ?

Thanks

**Comment by corpulentcoffee** [comment]
Hello!

I took a look at their [demo](http://www.ispeech.org/text.to.speech) and [API plans page](https://www.ispeech.org/developer/purchase/plans).

The API is expensive. It could still be an option if you have already bought an API key and would be willing to share it while I add support for iSpeech to AwesomeTTS (my e-mail address is in my GitHub profile).

The demo appends extra stuff to the output, so unless it can be reliably cut, it isn't a great option.

Cheers!

**Comment by lucwastiaux** [comment]
I do have a paid API key, emailed you. Agreed that it's expensive, but I haven't found an equivalent API for cantonese (let me know if I missed one).

**Comment by corpulentcoffee** [comment]
Great! I will look at adding support for this very soon. I will post a
build of the add-on here that you can test, too.

Thanks!

**Comment by corpulentcoffee** [comment]
Hello @lucwastiaux --

I now have a test branch with iSpeech working in AwesomeTTS. Please feel free to try it if you want to help test.

1. close Anki
2. find your Anki add-ons directory (usually your documents, then `Anki`, then `addons`)
3. download https://github.com/AwesomeTTS/AwesomeTTS/archive/ispeech-93.zip
4. open the archive
5. navigate into `AwesomeTTS-ispeech-93` then `addon`
6. copy `AwesomeTTS.py` and `awesometts` into your Anki add-ons directory
7. restart Anki

Let me know how things go.

Cheers!

**Comment by lucwastiaux** [comment]
Works beautifully for me, thanks !! Is the 30 second wait after 10 flashcards mandated by the API ?

**Comment by corpulentcoffee** [comment]
Hey @lucwastiaux --

No, it's not. I pushed a fix that exempts iSpeech from the throttling (which is appropriate, as it is a user-paid-for API).

If you re-download the package, the throttling should be gone.

**Comment by lucwastiaux** [comment]
It's working beautifully for me. Thanks for working on this. will you merge to the master branch ?

**Comment by corpulentcoffee** [comment]
Yes! I am planning on merging it and then releasing it with v1.8.

Before I merge it, I am going to add some documentation for it. I also know that there is at least one thing that needs fixing up (if you use a bad API key -- and maybe also if you need to refill your account -- AwesomeTTS just says "got 202 status" right now, which isn't very friendly).

Thank you so much for suggesting the service, for sharing your key, and for helping test.
