### ISSUE TITLE
Several languages

### ISSUE THREAD

**Issue by srzh** [AwesomeTTS/AwesomeTTS#96]
What about setting up TTS through CSS classes, not via tags, so to use any combination of languages on html (or at least skip unspeakable)? 

And control playback for different cards through CSS classes too. So not to play sound if tag inherits some class.

**Comment by corpulentcoffee** [comment]
Hello!

When running in on-the-fly speech mode, AwesomeTTS parses the HTML document of your cards to determine what to speak, so technically speaking, AwesomeTTS could be modified to use other signals.

Today, the signal just happens to be `<tts>...</tts>`.

What sort of problems are you trying to tackle by using e.g. `<p class='tts-baidu'>...</p>` instead of something like `<tts preset='baidu'>...</tts>`? Maybe there is another way to do what you want to do.

**Comment by srzh** [comment]
I want to choose what to speak by editing note, not when making template.
18 Мар 2016 г. 4:30 пользователь "Dave Shifflett" <notifications@github.com>
написал:

**Comment by corpulentcoffee** [comment]
Hi @srzh --

One method is to define some presents and/or groups (main Anki window > Tools > AwesomeTTS > Advanced > Service Presets and Groups) and then use those in your templates.

For example, if you make a preset called `en` and a preset called `fr`, then you could have a template like `<tts preset="{{Preset}}">{{Front}}</tts>`, and then your note's `Preset` field just needs to be set to the either `en` or `fr` for AwesomeTTS to figure out which language you want to use.

Anki also supports a special `{{Deck}}` placeholder. So if your cards are already arranged into decks for different languages, you could do `<tts preset="{{Deck}}">{{Front}}</tts>`, and then you just need to have a present named after each of your decks.

**Comment by srzh** [comment]
I'm talking about possibility to control card, not template. Sure, it require templates too. I was using many fields on my cards, now I'm on the other side, and my notes have only two fields, with first only as key/sort. I hide/show something through CSS. And yes, it's not enough, but for now only due to TTS.

**Comment by srzh** [comment]
In two words: bilingual texts.

**Comment by srzh** [comment]
Here what I was pointed to on similar topic:
https://github.com/ankidroid/Anki-Android/issues/1463#issuecomment-153290180

**Comment by srzh** [comment]
I want if some element have special class, say 'mute', no elements under it in the HTML tree should be spoken. Except may be those, that have have other explicit class, say 'speak'.

**Comment by corpulentcoffee** [comment]
Hi @srzh --

> I want if some element have special class, say 'mute', no elements under it in the HTML tree should be spoken. Except may be those, that have have other explicit class, say 'speak'.

You can accomplish this by modifying `awesometts/gui/reviewer.py` like this:

```patch
diff --git a/addon/awesometts/gui/reviewer.py b/addon/awesometts/gui/reviewer.py
index 64be139..33b0cff 100644
--- a/addon/awesometts/gui/reviewer.py
+++ b/addon/awesometts/gui/reviewer.py
@@ -237,16 +237,26 @@ class Reviewer(object):
     def _play_html_tag(self, tag, from_template, playback, parent,
                        show_errors=True):
         """Helper method for _play_html()."""
 
         text = from_template(unicode(tag))
         if not text:
             return
 
+        # Starting with this tag, check for 'speak' and 'mute' control classes
+        # in the hierarchy. The innermost control class takes precedence over
+        # any outer classes. If neither is found, this tag will play normally.
+        for control_tag in [tag] + tag.findParents():
+            control_classes = dict(control_tag.attrs).get('class', '').split()
+            if 'speak' in control_classes:
+                break
+            elif 'mute' in control_classes:
+                return
+
         attr = dict(tag.attrs)
         config = self._addon.config
 
         if 'group' in attr:
             try:
                 group = lax_dict_lookup(config['groups'], attr['group'])
             except KeyError:
                 if show_errors:
```

If you want to try this, you can [download this modified `awesometts/gui/reviewer.py` module](https://raw.githubusercontent.com/AwesomeTTS/AwesomeTTS/mute-speak-control-classes/addon/awesometts/gui/reviewer.py) and save it over top of your existing `Documents/Anki/addons/awesometts/gui/reviewer.py` file.

**Comment by srzh** [comment]
Wonderful!
But it looks only outside TTS tag, making whole thing virtually useless.
At least what it does for me.
The point is to look outside every HTML tag (with strings of course) which resides in the TTS tag.

**Comment by corpulentcoffee** [comment]
Hello!

You can walk children of the `<tts>` tag looking for `mute`/`speak`, too, like this:

```patch
diff --git a/addon/awesometts/gui/reviewer.py b/addon/awesometts/gui/reviewer.py
index 64be139..7e4a459 100644
--- a/addon/awesometts/gui/reviewer.py
+++ b/addon/awesometts/gui/reviewer.py
@@ -237,9 +237,36 @@ class Reviewer(object):
     def _play_html_tag(self, tag, from_template, playback, parent,
                        show_errors=True):
         """Helper method for _play_html()."""
 
-        text = from_template(unicode(tag))
+        def get_text_from_tag(start_tag):
+            """
+            Starting with this tag, check for 'speak' and 'mute' control
+            classes in the hierarchy. The innermost control class takes
+            precedence over any outer classes. If neither is found, this
+            tag will be included normally.
+            """
+
+            read_our_text = True
+            for control_tag in [start_tag] + start_tag.findParents():
+                control_classes = dict(control_tag.attrs).get('class', '')
+                control_classes = control_classes.split()
+                if 'speak' in control_classes:
+                    break
+                elif 'mute' in control_classes:
+                    read_our_text = False
+                    break
+
+            text_here = ''
+            for content in start_tag.contents:
+                if isinstance(content, basestring):
+                    if read_our_text:
+                        text_here += content
+                else:
+                    text_here += get_text_from_tag(content)
+            return text_here
+
+        text = from_template(get_text_from_tag(tag))
         if not text:
             return
 
         attr = dict(tag.attrs)
```

I updated [the modified `awesometts/gui/reviewer.py` module](https://raw.githubusercontent.com/AwesomeTTS/AwesomeTTS/mute-speak-control-classes/addon/awesometts/gui/reviewer.py) if you want to try using it over top of your existing `Documents/Anki/addons/awesometts/gui/reviewer.py` file.

**Comment by srzh** [comment]
Great! Thank you a lot.

Yes, it works as expected, though I didn't examined it well.
eSpeak on Linux is trying to read cyrillic in mixed english/russian text as raw unicode data, while Windows just skipping it silently. So marking whole field to mute and then marking english text to be spoken makes good.

But now I have a better idea to share with you.
I don't know if we can open new issue and close this one.

The idea is to add filter, and better with chaining mechanism. So one could add own transformation to text to be spoken in own addon. 
Not sure if Anki is supporting filter chaining.

I believe that would be more flexible and useful for many others.

But as simple mechanism, current variant should be useful too.

**Comment by corpulentcoffee** [comment]
I am scared that complex filter/chaining systems will be hard for most learners to use.

(For what it's worth, AwesomeTTS already has an "easy" way to filter out unwanted text from being read: you can mark a text within brackets or parentheses and then enable the "Strip off text within ..." options in Tools > AwesomeTTS > Text. I *think* this would be easier for most users than trying to explain CSS classes and HTML document structure to them.)

**Comment by srzh** [comment]
Sure, filtering system is for addons writers, who may accomplish other's requests, like you did for my modest one.

Thank you very much for help, waiting to see changes on Anki addons site.

**Comment by corpulentcoffee** [comment]
@srzh The new v1.8.0 release today will not include support for the `speak`/`mute` classes, so if you want to upgrade and you still want this feature, I have [updated the `awesometts/gui/reviewer.py` module](https://raw.githubusercontent.com/AwesomeTTS/AwesomeTTS/stable+mute-speak-classes/addon/awesometts/gui/reviewer.py) for you. You can apply it after upgrading.

**Comment by srzh** [comment]
Thank you.
