### ISSUE TITLE
Add ability to silence error messages / Recommend an in-order group-of-presets when a dictionary service doesn't have a word

### ISSUE THREAD

**Issue by ChristianKleineidam** [AwesomeTTS/AwesomeTTS#97]
![screenshot 10](https://cloud.githubusercontent.com/assets/5765379/14226619/fd05aaae-f8e6-11e5-835c-50a3a1df9da8.png)

I would like there to be an option with a tick box saying "Don't show this error message again".

**Comment by corpulentcoffee** [comment]
Hey @ChristianKleineidam --

That's a good idea. Today, however, there are two other options you might find helpful:

- go to the Anki main window > Tools > AwesomeTTS > Playback and untick "show errors" in the "Questions / Front of Cards" and/or "Answers / Back of Cards" sections<br><br> **or**<br><br>
- setup AwesomeTTS to play Oxford if possible with a fallback to some other service
    1. create a [service preset](https://ankiatts.appspot.com/usage/presets) for Oxford
    2. create a service preset for some other text-to-speech service that always generates output (basically any of them that aren't just a dictionary)
    3. create an [present group](https://ankiatts.appspot.com/usage/groups) that is set to play **in-order**: first Oxford preset, and then falling back to the alternative preset
    4. change your template tag from <br> `<tts service="oxford" voice="en-US">` <br> to <br> `<tts group="whatever you called your group">`

Hope one of those helps for now.

**Comment by ChristianKleineidam** [comment]
Thanks you. Creating a group with fallbacks is indeed the correct solution for my usecase. I think it would be great if the error message highlites the fact that AwesomeTTS supports this great feature.

**Comment by corpulentcoffee** [comment]
That's a good idea. I will change the error message for the various dictionary services (e.g. Howjsay, Oxford) to bring more attention to the preset/groups features.
